name: 'Deploy website'
on:
  workflow_dispatch:
    inputs:
      just-deploy:
        description: 'Just deploy (overrides skip)'
        type: 'boolean'
        required: true
        default: false
      skip-deploy:
        description: 'Skip deploy'
        type: 'boolean'
        required: true
        default: false
  push:
    branches:
      - 'main'
    paths:
      - 'Guides/**'
      - 'ExtraInfo/**'
jobs:
  generate:
    name: 'Generate chip markdown'
    runs-on: 'ubuntu-latest'
    if: ${{ !inputs.just-deploy }}
    permissions:
      contents: 'write'
    outputs:
      commit-sha: '${{ steps.commit-push.outputs.commit-sha }}'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
        with:
          repository: '${{ github.repository }}'
          ref: 'main'
          ssh-key: '${{ secrets.BR_BYPASS }}'
      - name: 'Setup Node'
        uses: 'actions/setup-node@v3'
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './Source'
      - name: 'Run script'
        working-directory: './Source'
        run: |
          npm ci
          npm run generate
      - name: 'Commit and push'
        id: 'commit-push'
        continue-on-error: true
        #cp ./Source/Generated/info.txt ./Generated/ is this even generated?
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "actions-user"
          cp ./Source/Generated/chips.json ./Generated/
          cp ./Source/Generated/ports.json ./Generated/
          git add Generated
          git add Circuits/docs
          git add ExtraInfo
          git commit -m "[no ci] Generated markdown and svg - based on ${{ github.sha }}"
          git push
          echo "commit-sha=$(git log --format='%H' -1)" >> "$GITHUB_OUTPUT"
  deploy:
    name: 'Deploy (Production)'
    runs-on: 'ubuntu-latest'
    needs: 'generate'
    if: ${{ !failure() && (!inputs.skip-deploy || inputs.just-deploy) }}
    permissions:
      contents: 'read'
      deployments: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
        with:
          ref: '${{ needs.generate.outputs.commit-sha || github.sha }}'
      - name: 'Setup Node'
        uses: 'actions/setup-node@v3'
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './Circuits'
      - name: 'Build'
        working-directory: './Circuits'
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm ci
          npm run build
      - name: 'Deploy to Cloudflare Pages'
        uses: 'cloudflare/pages-action@v1.5.0'
        with:
          apiToken: '${{ secrets.CLD_FLR_TKN }}'
          accountId: '${{ secrets.CLD_FLR_ID }}'
          projectName: 'circuits'
          branch: 'main'
          directory: './build'
          workingDirectory: './Circuits'
          gitHubToken: '${{ secrets.GITHUB_TOKEN }}'
