name: 'Test build for when breaking changes may be suspected'
on:
  workflow_dispatch:
concurrency:
  group: 'test-build'
  cancel-in-progress: true
jobs:
  test-build:
    name: 'Test build'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
      - name: 'Setup Python'
        uses: 'actions/setup-python@v5'
        with:
          python-version: '3.10'
          cache: 'pipenv'
          cache-dependency-path: './Source/Pipfile.lock'
      - name: 'Install pipenv and setup environment'
        working-directory: './Source'
        run: |
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
          pipenv install
      - name: 'Download source JSON file and run Python scripts'
        working-directory: './Source'
        run: |
          curl https://raw.githubusercontent.com/tyleo-rec/CircuitsV2Resources/master/misc/circuitsv2.json -o source_data.json
          pipenv run python Translate_JSON.py ./source_data.json ./Generated/chips.json ./Generated/ports.json
          pipenv run python Generate_Docs.py
      - name: 'Setup Node'
        uses: 'actions/setup-node@v4'
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './Circuits/package-lock.json'
      - name: 'Build'
        working-directory: './Circuits'
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm ci
          npm run build
